"""empty message

Revision ID: 10a5a491cf9d
Revises: be80ac44035f
Create Date: 2022-04-16 04:02:47.961218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a5a491cf9d'
down_revision = 'be80ac44035f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('type_text', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('type_voice', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('dm_channel', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('private_channel', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'private_channel')
    op.drop_column('channels', 'dm_channel')
    op.drop_column('channels', 'type_voice')
    op.drop_column('channels', 'type_text')
    op.drop_column('channels', 'owner_id')
    # ### end Alembic commands ###
