"""empty message

Revision ID: 1c7caa6d1c4a
Revises: f536021aebe3
Create Date: 2022-04-20 02:33:08.315680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7caa6d1c4a'
down_revision = 'f536021aebe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channelMessages', sa.Column('picture', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channelMessages', 'picture')
    # ### end Alembic commands ###
