"""empty message

Revision ID: 7c7be27371e4
Revises: d0e12690d577
Create Date: 2023-04-07 06:08:06.103510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7be27371e4'
down_revision = 'd0e12690d577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity', sa.String(length=10), server_default='offline', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity')
    # ### end Alembic commands ###
