"""empty message

Revision ID: ab9f6ec56595
Revises: e567ea67b355
Create Date: 2022-04-12 02:07:41.579430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9f6ec56595'
down_revision = 'e567ea67b355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_owner_id_fkey', 'channels', type_='foreignkey')
    op.drop_column('channels', 'description')
    op.drop_column('channels', 'topic')
    op.drop_column('channels', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key('channels_owner_id_fkey', 'channels', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
