"""empty message

Revision ID: d0e12690d577
Revises: 1c7caa6d1c4a
Create Date: 2022-04-20 18:16:56.936419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e12690d577'
down_revision = '1c7caa6d1c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('private_server', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'private_server')
    # ### end Alembic commands ###
