"""empty message

Revision ID: e567ea67b355
Revises: 3f4dcbfb6305
Create Date: 2022-04-12 01:30:32.079786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e567ea67b355'
down_revision = '3f4dcbfb6305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serverDmMembers')
    op.drop_table('serverDms')
    op.drop_table('serverDmRooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serverDmRooms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"serverDmRooms_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='serverDmRooms_owner_id_fkey'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name='serverDmRooms_server_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='serverDmRooms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('serverDms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"serverDms_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['serverDmRooms.id'], name='serverDms_room_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='serverDms_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='serverDms_pkey')
    )
    op.create_table('serverDmMembers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"serverDmMembers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['serverDmRooms.id'], name='serverDmMembers_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='serverDmMembers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='serverDmMembers_pkey')
    )
    # ### end Alembic commands ###
